version: '3.8'
services:
  frontend:
    container_name: frontend 
    restart: always
    build: ./frontend
    ports:
      - ${VPORT}:${VPORT}
    depends_on:
      - db 
    networks: [ "microservices" ]


  backend:
    container_name: backend
    restart: always
    build: ./backend 
    ports:
      - ${GPORT}:${GPORT}
    depends_on:
      - db
    networks: [ "microservices" ]

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks: [ "microservices" ]
 
volumes: 
 data: {}
 frontend: {}
 backend: {}
networks:
  microservices:
    name: microservices
